name: CI

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - VERSION
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - VERSION
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grab the version to use.
        id: vars
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Get timestamp for CI tag
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Build the Docker image.
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
          tags: dcjulian29/openssl:${{ steps.vars.outputs.version }}-${{ steps.format-time.outputs.replaced }}
