name: Release

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: vars
        run: echo "::set-output name=version::$(echo ${GITHUB_REF:10})"

      - name: Build and push the Docker image.
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
          context: .
          push: true
          tags: |
            dcjulian29/openssl:${{ steps.vars.outputs.version }}
            dcjulian29/openssl:latest
