---
name: OpenSSL Tool

'on':
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - VERSION

  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - VERSION

jobs:
  build:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    name: Build Tool
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: build --snapshot --clean
          distribution: goreleaser
          version: '~> v2'

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Release Tool
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - name: Grab the version to use.
        id: vars
        run: |
          Write-Output "version=$(Get-Content ${{ github.workspace }}\VERSION)" `
            | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding UTF8 -Append

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
          IMAGE_VERSION: ${{ steps.vars.outputs.version }}
